### ISSUE TITLE
Wrong flag next to account?

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#103]
I have a canadian currency account but it shows the US flag next to it.
A little confusing ...

![image](https://user-images.githubusercontent.com/37969784/228527774-d6794019-bd89-4bf4-8d7a-28005cbf2d9b.png)

**Comment by andreva7** [comment]
It seems the flag is not working at all anymore:
I set the currency on one account that had it blank.
Instantly all accounts had a US flag, no matter whether they were USD, CAD or blank.
I then changed the  display currency from USD to CAD, the flag is still US everywhere.
Restarted the App, still same behaviour.

**Comment by jpdup** [comment]
I'll investigate

**Comment by jpdup** [comment]
I was not able to reproduce this bug.  Can you share the screen that you see on "View->Currencies"  for example here's mine
![image](https://user-images.githubusercontent.com/2709213/228638736-84cddbe5-8abb-4ea0-9c47-2c86bf12bd6e.png)

**Comment by andreva7** [comment]
***@***.***

***@***.***

**Comment by jpdup** [comment]
Not sure what that last comment was about

**Comment by clovett** [comment]
I was able to reproduce the problem with sample data.  Since we default to USD, all sample accounts show "USD" on the right, but no flag, since the flag requires explicit currency be set. I fixed the problem with currency flag not showing up on accounts that have no currency specified, it should default to US dollar.

**Comment by andreva7** [comment]
Culture code for CAD was set to en-US. I fixed that and canada flags show up now.
Maybe add a warning or error if two currencies have the same culture code?

**Comment by clovett** [comment]
Note that if you enter a new row for Canadian dollars, it defaults to "en-CA", so I think this should be good for other users that didn't already have the CAD entered in the Currencies view.

![image](https://user-images.githubusercontent.com/3336415/233243876-37418348-632b-4e1e-b48f-6ca352f6c182.png)
