### ISSUE TITLE
Can't type in 13,024.92

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#104]
I have a transaction, which is a transfer from one account to another.
I can not set the value in the transaction to 13,024.92. When I set that value, is put's in 13,024.90 instead.
3.92 works
13.92 works
1302.92 works
13024.92 -> my money switches it to 13024.90
13024.98 -> my money switches it to 13025.00

Something wants to round that number.
I did check the currency is set to USD on both accounts.

**Comment by andreva7** [comment]
Did more troubleshooting. Definitely a rounding problem on processing input:

9,999.99 is OK
10,000.01 becomes 10,000.00
10,000.09 becomes 10,000.10
888,888,88 becomes 888,889.00

**Comment by clovett** [comment]
Fixed in 2.1.0.11
