### ISSUE TITLE
feature: Previously used databases

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#105]
I actively work on two different MyMoney databases. Mine, and the PTA. I would like to optimize switching between these databases.
Right now I launch MyMoney, go through file open and navigate the file tree to open the other database. Some days I end up doing that 3 or 4 times.

Double clicking on a DB and having MyMoney launch on that DB would be great, but it does not work on my machine (is that something  that is possible?)

If not, can we add a way to pin some database files in the open dialog, or have my money automatically remember the last few databases that were opened.

**Comment by clovett** [comment]
Double clicking on the *.mmdb file should work so long as you have already make mymoney the default app for this file type.  You  can do that using the File menu item:
![image](https://user-images.githubusercontent.com/3336415/233234963-197a51a6-a7ef-4a98-a779-8c306d468e3d.png)

You will know file association is working if the icon for the .mmdb file looks like this in Windows explorer:
![image](https://user-images.githubusercontent.com/3336415/233235023-6fca3ba6-e494-4e28-93a1-9d2a0289a9ef.png)

The app also has a "Recent Files" menu under the main File menu where you can easily select recently opened money files and toggle between them.

**Comment by clovett** [comment]
If the file association is not working automatically you can repair it using right click "Open With" -> "Choose another app":
![image](https://user-images.githubusercontent.com/3336415/233235397-79189469-09ae-47c1-adb4-a202b6608a0c.png)
scroll down to 
![image](https://user-images.githubusercontent.com/3336415/233235444-f82729a7-2dca-4aac-bd4d-a3abe833c521.png)
and the trick is finding the app in the Click once install folder.  The easiest way to find it is to right click a running instance in the task bar and select Properties.  The "Location" will look like this: "C:\Users\lovet\AppData\Local\Apps\2.0\6C6M27MH.8M4\0Q4Z39WX.9JK\mymo..tion_d2e0d325f5b08396_0002.0001_472f4cce3711ad14"

Then check it shows up in this Windows settings dialog:
![image](https://user-images.githubusercontent.com/3336415/233235250-3f3639f6-7616-4218-abef-37459c4492f6.png)

**Comment by andreva7** [comment]
Oops :-(
