### ISSUE TITLE
math problem editing splits

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#107]
When I edit a split, I end up with this very small discrepancy in amounts.
If I save, close and restart MyMoney, then the error goes away.
But If I edit again, the same discrepancy reappears.

![image](https://github.com/MoneyTools/MyMoney.Net/assets/37969784/979d3533-3017-4687-bd0a-43711fdd6323)

**Comment by jpdup** [comment]
Interesting ...
I'll try to look on it this weekend

**Comment by lovettchris** [comment]
I pushed a fix.

**Comment by lovettchris** [comment]
Fixed in https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.12
