### ISSUE TITLE
Attach pdf files to register entries

### ISSUE THREAD

**Issue by Mojavedx** [MoneyTools/MyMoney.Net#115]
Is it possible to integrate attach pdf to the register attachments entries instead of using a scanner. I would like to be able to attach my pay stubs to my salary entries that are in split transaction form. If not. Is it possible to attach multiple  pdf documents during the reconciliation instead of 1 bank statement.

**Comment by clovett** [comment]
Yes, I've needed this also, done.  You can now add any file type and you can double click the attachment in the Attachment DIalog to open that file in the windows registered viewer for that file type.

This is published in [version 2.1.0.22](https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.22)
