### ISSUE TITLE
Missing unknown transactions to account expense

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#116]
Select an account, like a credit card account
In the right bottom frame select expenses.
The pie chart and total only reflects expenses that are categorized.
I think adding the uncategorized entries to the pie chart as well would give a more accurate representation of the account.

**Comment by clovett** [comment]
Good idea, fixed in "[2.1.0.19](https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.19)"  you will now see a new "**Unassigned**" category in the legend which you can click on to see only those transactions.

**Comment by andreva7** [comment]
Works great - thank you.
