### ISSUE TITLE
Categories w/ type RecurringExpense are hidden from the category left-nav.

### ISSUE THREAD

**Issue by monomolecular** [MoneyTools/MyMoney.Net#117]
When setting up my categories in the Windows app, if I set the category type to RecurringExpense it disappears from the category left-nave. It's still possible to find via other mechanisms, e.g. editing an individual transaction.

**Comment by jpdup** [comment]
Note that this repros well when the RecuringExpense is set as top level Category

**Comment by clovett** [comment]
Fixed in 2.1.0.20
