### ISSUE TITLE
Transaction.originalPayee

### ISSUE THREAD

**Issue by jpdup** [MoneyTools/MyMoney.Net#118]
What is the Purpose of the field `Transaction.originalPayee`?
 
I looked at the .Net code and did not see anything obvious, I was expecting this field to be a snapshot of the original Payee that was first received from download, or before having the Payee mutated by user editing it or auto-renamed

**Comment by clovett** [comment]
This comment should help:
```
private string originalPayee; // before auto-aliasing, helps with future merging.
```
It remembers the downloaded version of the Payee field so that next time you download these same transactions it is better at merging transactions (remember the visible Payee can be changed by auto-aliasing and so this helps).

**Comment by jpdup** [comment]
Yes, right. Thanks for confirming.
The Windows version does not seem to expose/display the OriginalPayee anywhere for the user to see what it was before the Auto-Alteration, correct?

On the Flutter version, I'm about to embark on implementing a new UX that will allow more retro-adjustments of OriginalPayee to New-Value. This way, the user can change their mind or try out different scenarios. This request comes from @Max Kanter, a new user of Money.

I'm also going to keep track of OriginalPayee even if it was not originally obtained by OFX import.

**Comment by clovett** [comment]
Yep, sounds cool, there definitely have been times when I've needed that also when an Alias kicked in, but I disagree with the auto-aliasing and want to know what the original value was.  I have been using the memo field to store that, but sometimes the memo is populated by the bank, so it's not always available.  So yeah, an "undo alias" feature would be nice.
