### ISSUE TITLE
Accept all

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#119]
I recently discovered the usage of accepted transactions.
I have over 10,000 unaccepted transactions. :-(

1. Could\should there be an option to accept all transactions in a particular account. 

2. When one balances an account, should the transactions be accepted automatically? Or at least have an option to do so (a little check mark), that's on by default?

Thanks.

**Comment by clovett** [comment]
1. good idea, will add it.
2. this is an option under View/Options:
![image](https://github.com/MoneyTools/MyMoney.Net/assets/3336415/9ea23e9d-a0b4-4320-be37-76afeea7446a)

**Comment by clovett** [comment]
Implemented in 2.1.0.20
