### ISSUE TITLE
Why exclude special characters "{ } :" for Account Name 

### ISSUE THREAD

**Issue by jpdup** [MoneyTools/MyMoney.Net#121]
In the flutter version we use ':' to tokenize the names for Category and Account, it has the benefit of doing nice rendering like this.

![image](https://github.com/MoneyTools/MyMoney.Net/assets/2709213/f0356c81-1f97-4962-b94b-6d5596232ae0)

![image](https://github.com/MoneyTools/MyMoney.Net/assets/2709213/2865e2a1-1787-4c22-8233-df5debdd3b0b)

Looking at the code for Account dialog, the name is not allowed to have ':',   Is this a legacy reason for serialization ?
Would this limitation also be applicable to Category names ? which is allowed to have ':' 

Can we remove this limitation?

```
private static readonly char[] InvalidNameChars = new char[] { '{', '}', ':' };

  private void OnNameChanged(object sender, TextChangedEventArgs e)
  {
      this.CheckButtonStates();

      if (this.TextBoxName.Text.IndexOfAny(InvalidNameChars) >= 0)
      {
          this.TextBoxName.Background = Brushes.Red;
          this.TextBoxName.ToolTip = Walkabout.Properties.Resources.AccountNameValidChars;
          this.ButtonOk.IsEnabled = false;
      }
      else
      {
          this.TextBoxName.ClearValue(TextBox.BackgroundProperty);
          this.TextBoxName.ToolTip = "";
      }
  }
```

**Comment by clovett** [comment]
Because the account name has to also be a valid windows folder name because that's where we store the statements and attachments.
