### ISSUE TITLE
Historical investment portfolio does not handle stock splits correctly

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#132]
Find any stock that has a stock split in your accounts
In the investment portfolio report, set the date to after the stock split, look at the stock in question, then set the date before the stock split and look at the stock. The price and share count should be inversely affected and the overall value of the shares about the same (minus price fluctuation).

I have two repros, behaving differently :-(  where either the price is not set correctly or the share count is not.

**Comment by clovett** [comment]
Oh, interesting, TwelveData is returning a "split adjusted stock price history" like you see in this chart:

[Microsoft - 38 Year Stock Price History | MSFT | MacroTrends](https://www.macrotrends.net/stocks/charts/MSFT/microsoft/stock-price-history)

But for portfolio reports that go back in time I need to use the unadjusted prices you see in this chart:

[Microsoft - 38 Year Stock Split History | MSFT | MacroTrends](https://www.macrotrends.net/stocks/charts/MSFT/microsoft/stock-splits)

This will take some work to fix...

**Comment by clovett** [comment]
I pushed a fix and published [new version 2.1.0.33 ](https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.33) where the historical portfolio report is now correct.

**Comment by andreva7** [comment]
Looks good! Thanks
