### ISSUE TITLE
Need a Cross platform version of MyMoney

### ISSUE THREAD

**Issue by jpdup** [MoneyTools/MyMoney.Net#5]
Hello Mr Lovett.

This is my official request to join the MyMoney project and possibly add new Companion versions of this great Finance app

**Comment by grahamehorner** [comment]
@jpdup isn’t great to see this as an open source project? thanks @clovett  
@jpdup maybe it would be cool to look into creating a #blazor (server-side razor) 
app using .net  core

**Comment by clovett** [comment]
See https://github.com/MoneyTools/MoneyFlutter
