### ISSUE TITLE
Accounts context menu

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#73]
When you right click on an account, the menu that comes down has a mix of specific account options (Balance, delete account, export account) and general account options (new account, export list).
It might be better to have just one separator in the list, because on the above categorization

**Comment by clovett** [comment]
This is the current design:

![image](https://user-images.githubusercontent.com/3336415/224531487-b9121785-416c-42f3-873e-a3889e0d1376.png)

**Comment by clovett** [comment]
So how about this cleanup then:

![image](https://user-images.githubusercontent.com/3336415/224531627-2a865bde-e539-4d42-8bb7-62ce25913463.png)

**Comment by clovett** [comment]
I've implemented this last proposal.
