### ISSUE TITLE
Legal export

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#74]
The statement linking has been great - 45 directories, 1310 statements linked.
It's the foundation of what gets presented at trial.

I have been taking to my lawyer some more and now understand what it takes to get ready for a trial:

When you present financial information at a trial, the judge expects to have all financial information stored in .pdf files (no other file type. I have been convertind non .pdf files to pdf files. Question: Can I just go in the XML and change the extension of the files to pdf, and manually overwrite the original file with the pdf one? The hash file will be wrong, but will that break anything (assuming there was no single instancing)

In the court documents, each financial account is one Exhibit.
Each Exhibit is a single PDF file, which contains all pdf statements for that one account merged together, with the first financial statement in the file being the most recent and the last statement being the oldest. So yes, you get pdf files that are hundreds of pages long.

Then each of these .pdf files is bates numbered.

Right now we have an index.xml file for each account, sorted from oldest to newest, which is great.

The feature request would be to build in some part of : (1) extract the list of file names in the index file, (2) reverse the order, and then (3) call some pdf APIs to create a merged document. When done, call (4) some other tool to add a bates number to each page.

Any interest in any part of that work in mymoney? The feature would be called "legal export" as an account feature. Just (1) and (2) would be useful as it would remove the need to write an XML parser and text outputer. I see (3) and (4) being a bit harder. I've spend a few hours searching APIs and apps that manipulate pdf files. It seems there are a lot, but I have not yet found anything super easy to integrate, like a library.

**Comment by andreva7** [comment]
oohhh, found this:

http://www.pdfsharp.net/wiki/ConcatenateDocuments-sample.ashx

**Comment by clovett** [comment]
Regarding the overall "export one big pdf of all account statements" feature, I'd be happier if this was a separate tool, perhaps you just point it at the statements folder and it works through the whole folder using the statement indexes to order them correctly.

In terms of the hash values in the statement indexes, you can force the <Hash>...</Hash> values to be updated if you remove these XML elements from the Statement Index.
