### ISSUE TITLE
chase credit card download stopped working

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#75]
Do you have a chase credit card? download stopped working a few days ago. I get the message "The remote name could not be resolved: 'ofx.chase.com'"
This sounds like a problem at their end, but would be nice to confirm if someone else is seeing the same thing.

**Comment by clovett** [comment]
I do not, hopefully the bank still provides an "OFX export" option on their download menu.  That's what I have to do with my Discover and VISA accounts.  Best I can advise is that you complain vehemently that banks continue to allow you to get access to your data via OFX.  I did this at my local credit union BECU - and they turned it back on again which is nice.  But haven't had any luck finding a real human at Discover or VISA...

I see an error report here involving SSL certs:
> https://www.ofxhome.com/index.php/institution/view/636

So it would be handy to get any logs from this failure, and even debug stack traces and details of the inner most WebRequest exceptions to see if we can get any hints from there.  Sometimes it has been a .NET Framework versioning issue where the old framework doesn't support the latest SSL standards.  So we should try and rule that out.

Also, sometimes repeating the "Connect" steps via the connect dialog can solve the problem too:

![image](https://user-images.githubusercontent.com/3336415/195003019-eb68654a-0ec8-43fd-80a3-911e109dff5f.png)

**Comment by andreva7** [comment]
The OFX address https://ofx.chase.com/ for Financial Instutition B1 returned the following error message:

System.Net.WebException: The remote name could not be resolved: 'ofx.chase.com'

Response
at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context) at System.Net.HttpWebRequest.GetRequestStream() at Walkabout.Ofx.OfxRequest.SendOfxRequest(XDocument doc, String oldFileUid, String newFileUid) at Walkabout.Ofx.OfxRequest.Sync(IList accounts, OfxDownloadData results, Dispatcher dispatcher) at Walkabout.Ofx.OfxThread.SyncAccount()

HTTP Headers
More Information
You may search for more information about your financial institution by visiting [OFX Home](http://www.ofxhome.com/) .

**Comment by clovett** [comment]
Ok, it means they either shutdown their OFX gateway (complain loudly) or they moved to to a new location.  There is some info here: https://wiki.gnucash.org/wiki/OFX_Direct_Connect_Bank_Settings#Chase_.28Bank_Accounts_and_Credit_Cards.29

**Comment by clovett** [comment]
Hey, cool, this GnuCash info about Citibank helped me get my Costco VISA card OFX download to work again:
https://wiki.gnucash.org/wiki/OFX_Direct_Connect_Bank_Settings#Citi_Credit_Card

Yay.

**Comment by clovett** [comment]
I fixed some bugs in OFX processing to help make Costco VISA card work, see https://github.com/clovett/MyMoney.Net/commit/0aed80a028a5c8f15ff916d071696d4877bdb497

**Comment by clovett** [comment]
I also added a new feature, general csv importing, see https://clovett.github.io/MyMoney.Net/#Accounts/CsvImport/

**Comment by clovett** [comment]
That's as much as I can do on these kinds of issues.  The rest is up to Chase Bank.
