### ISSUE TITLE
Back button behaviour

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#85]
The back button does not work when the previous screen is a cashflow report. It would be very useful if it did :-)

**Comment by lovettchris** [comment]
I pushed a fix, reports are now included in the Back/Foward navigation.

**Comment by lovettchris** [comment]
Fixed in https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.12

**Comment by andreva7** [comment]
Awesome! thanks.
