### ISSUE TITLE
unhandled exception trying to rename an account

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#86]
![image](https://user-images.githubusercontent.com/37969784/211877903-6bb745ba-4816-4814-a5b2-3cc2222bb5da.png)

**Comment by jpdup** [comment]
Any repro steps?

**Comment by andreva7** [comment]
Right click on the account, properties, take out two characters from the name, press enter.

Note that I have reconciled statement files associated to this account.

The statement subdirectory does get renamed, but not the account name in mymoney. So things are inconsistent at that point (I go rename the directory to the old name to get back to the previous state.

**Comment by jpdup** [comment]
Thanks for the repro, I was able to hit the null pointer.
I pushed a fix to the main branch

**Comment by clovett** [comment]
Thanks JP, I published a new version with this fix: https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.0.1.10

**Comment by andreva7** [comment]
👍
