### ISSUE TITLE
Change overall currency view

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#87]
Would be great to have all the totals switch to be $CDN vs $US with a button click.

**Comment by jpdup** [comment]
Good idea, we can have a setting for default currency for example I now live in a 4 different countries and need 4 currencies 

US Canada Euro and UK

**Comment by andreva7** [comment]
To make this feature work, MyMoney would first need that ensures all accounts have a specific currency marked. It would need to be a lazy check because making the currency optional is nice in most scenarios, where people have all US except one or two others.

**Comment by clovett** [comment]
Fixed by https://github.com/MoneyTools/MyMoney.Net/pull/90
