### ISSUE TITLE
go to related transaction (F12) does not work

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#94]
"Go to related transaction" brings you to the correct other account, but not the transaction itself. The bottom (latest) transaction in the target account ends up highlighted.
Reproed many times for different transactions and account.

**Comment by lovettchris** [comment]
Yep this is related to #92 - I find it is a bit random sometimes it actually works but most of the time it does not, so yeah, something broke, I will investigate as soon as I get a chance.
